spring.application.name=zero-kanada-library

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.username=estraven
spring.datasource.password=Gethen17776*

server.port=8082

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG